version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: "circleci/python:3.10-browsers-legacy"
    steps:
      - checkout 
      - restore_cache:
          key: "{{ .Branch }}-test"
      - run:
          name: Install flask
          command: pip3 install flask
      - run:
          name: Verify flask
          command: pip3 list
      - run: echo "build done"
      - save_cache:
          key: "{{ .Branch }}-test"
          paths:
            - "venv"
  deploy:
    working_directory: ~
    docker:
      - image: "circleci/python:3.10-browsers-legacy"
    steps:
      - checkout
      - run: echo "deploy done"
workflows:
  version: 2

  dev_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          filters:
            branches:
              only: main
          requires:
          - build