version: 2.1

jobs:
  build:
    working_directory: ~
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: echo "build done"
  deploy:
    working_directory: ~
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: echo "deploy done"

workflows:
  dev_workflow:
    jobs:
      - build:
        filters:
          branch:
            only:
              - main
      - deploy:
        filters:
          branch:
            only:
              - main
        requires:
        - build